[package]
name = "polynomial-simd"
description = "Quickly evaluate polynomials using SIMD"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/TiagoCavalcante/polynomial-simd"
